/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * BFF -> grasp-search service input. Wire form uses camelCase.
 */
export interface GraspSearchRequest {
  /**
   * Internal contract version (see contract-version.json). Mismatch is rejected with 400.
   */
  contractVersion?: number;
  /**
   * Layout DSL schema version this declaration targets, e.g. 'layout/1.0'. References the public schema; not redefined here.
   */
  layoutVersion: string;
  graspSearch: GraspSearchDeclaration;
}
/**
 * The graspSearch declaration. Its detailed shape (hardConstraints / objectives) is owned by the Layout DSL schema named by layoutVersion; kept open here on purpose.
 */
export interface GraspSearchDeclaration {
  /**
   * objective name -> weight. Keys correspond to score breakdown keys.
   */
  objectiveWeights?: {
    [k: string]: number;
  };
  /**
   * How many ranked candidates to return (fallback material for the BFF).
   */
  topN?: number;
  /**
   * Declares the 'can it be reached' (Plan) domain judgement parameters (ADR-081 Sense/Plan/Act axis, forward-wrapped by ADR-084 §4). These were formerly written directly on `robot.*`; they move here so a later `sense{}`/`act{}` split does not have to move them again. Declaration only -- reach/IK evaluation stays solved in core/. Reading precedence: when a key is present in both `plan` and the legacy `robot`, `plan` wins (backward-compat fallback in the core adapter).
   */
  plan?: {
    reachMin?: number;
    reachMax?: number;
    wristConeHalfAngle?: number;
  };
  /**
   * Declares the resolved robot geometry (ADR-083/084). `base` and `tcpOrientation` are resolved from the Layout DSL CoordinateFrame entities on the front side (transformGraph composed to world pose) before being sent -- core/ never knows about entities. The judgement params (reach* /wristConeHalfAngle) moved to `plan{}` (ADR-084 §4); they are still accepted here as a backward-compat fallback. Reach/IK/cone evaluation itself stays solved in core/.
   */
  robot?: {
    /**
     * [x, y, z] world-frame position of the robot base (ROS convention, Z up). Resolved from the `robot_base` CoordinateFrame entity (ADR-084 §2).
     *
     * @minItems 3
     * @maxItems 3
     */
    base?: [number, number, number];
    /**
     * [x, y, z, w] world-frame quaternion of the gripper (TCP) pose, resolved from the `tcp` CoordinateFrame entity (ADR-084 §3). Same axis order as the response `cartesianFrame.orientation`. When declared, the naive cone judgement measures the required approach against the TCP forward axis (+X rotated by this quaternion) instead of the base->candidate proxy axis; omitting it keeps the legacy proxy-axis behavior (no silent change).
     *
     * @minItems 4
     * @maxItems 4
     */
    tcpOrientation?: [number, number, number, number];
    reachMin?: number;
    reachMax?: number;
    wristConeHalfAngle?: number;
  };
  /**
   * Declares the vision camera for the 'can it be seen' domain gate (ADR-081). Like `robot`, this only declares -- visibility evaluation itself is solved in core/. Optional: with no camera declared the visibility stage passes everything (rejectedByVisibility stays 0 and `visible` is vacuously true).
   */
  camera?: {
    /**
     * [x, y, z] world-frame position of the camera's optical center.
     *
     * @minItems 3
     * @maxItems 3
     */
    position: [number, number, number];
    /**
     * Optional viewing direction (need not be unit length; the solver normalizes). The field-of-view cone applies only when both viewAxis and fovHalfAngle are declared.
     *
     * @minItems 3
     * @maxItems 3
     */
    viewAxis?: [number, number, number];
    /**
     * Optional field-of-view half angle in radians (cone around viewAxis).
     */
    fovHalfAngle?: number;
  };
  /**
   * Declares the hand for the 'can it be grasped' domain gate (ADR-081), as a CLOSED KIND-DISCRIMINATED UNION (ADR-118, same governance as the response's `pose`). A parallel jaw and a suction cup do not measure the same quantity -- one asks whether the jaws close across the object, the other whether a flat enough patch of the surface can be sealed -- so they are separate branches rather than optional siblings on one flat object. Flattening them would make 'a suction cup with a jaw opening' representable. Declaration only: the gate itself is solved in core/. Optional as a whole: with no gripper declared the grasp stage passes everything (rejectedByGrasp stays 0 and `graspable` is vacuously true). The only intentional growth point is adding a kind, which bumps contractVersion.
   */
  gripper?: GripperParallelJaw | GripperSuction;
  [k: string]: unknown;
}
/**
 * Two-finger parallel jaw. The gate closes across the object, so the quantity that decides feasibility is the object width along the closing axis.
 */
export interface GripperParallelJaw {
  kind: "parallelJaw";
  /**
   * Maximum jaw opening width (same length unit as the request geometry).
   */
  maxOpening: number;
  /**
   * Extra clearance the fingers need to slide in beside the target (the naive gate requires maxOpening >= target width + fingerClearance).
   */
  fingerClearance?: number;
}
/**
 * Vacuum cup. The gate seals against a face, so the quantity that decides feasibility is whether a contiguous patch at least the cup diameter across is flat enough to seal -- width and finger clearance are meaningless here.
 */
export interface GripperSuction {
  kind: "suction";
  /**
   * Cup outside diameter -- the patch the seal needs (same length unit as the request geometry).
   */
  cupDiameter: number;
  /**
   * How far a surface normal inside the cup footprint may deviate from the contact normal and still seal, in radians. Absent leaves the solver its own naive default; it is never inferred from the other fields.
   */
  sealTiltTolerance?: number;
}
