/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * grasp-search service -> BFF output. Top-N ranking with score breakdown. Wire form uses camelCase.
 */
export interface GraspSearchResponse {
  /**
   * Internal contract version (see contract-version.json).
   */
  contractVersion?: number;
  /**
   * Ranked candidates, rank ascending (1 = best). Not a single best pose.
   */
  candidates: PoseCandidate[];
}
export interface PoseCandidate {
  rank: number;
  /**
   * The pose itself (joints / TCP). Opaque at the contract boundary; exact shape owned by the service implementation.
   */
  pose?: {
    [k: string]: unknown;
  };
  score: ScoreBreakdown;
}
/**
 * Per-candidate score breakdown explaining why a pose ranked where it did.
 */
export interface ScoreBreakdown {
  withinReach: boolean;
  ikSolvable: boolean;
  interferenceFree: boolean;
  /**
   * objective name -> normalized 0-1 value (absolute basis, so scores are comparable across requests).
   */
  objectiveScores?: {
    [k: string]: number;
  };
  /**
   * Weighted sum of the normalized objective scores.
   */
  totalScore: number;
}
