/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The pose the solver *decided*, as a closed kind-discriminated union. Only solver-decided facts ride the wire; presentation (approach vector, ghost color, gripper-width display, animation) is derived client-side from the frame + convention and is NOT part of this contract. The only intentional growth point is adding a new kind (which bumps contractVersion). kind is the discriminator; each branch is closed (additionalProperties:false). 'optional' is not a design word here -- field presence is implied by kind.
 */
export type Pose = PoseEndEffector | PoseJointSpace;

/**
 * grasp-search service -> BFF output. Top-N ranking with score breakdown. Wire form uses camelCase.
 */
export interface GraspSearchResponse {
  /**
   * Internal contract version (see contract-version.json).
   */
  contractVersion?: number;
  /**
   * Ranked candidates, rank ascending (1 = best). Not a single best pose.
   */
  candidates: PoseCandidate[];
  /**
   * Solver-decided facts about the search as a whole (the rejection funnel), so a client can explain an empty or thin result. Contract v4 (ADR-081) widens the funnel to the three validation domains -- visible (Vision) / reachable (Path: reach, IK, interference) / graspable (Grasp). Invariant: candidatesGenerated = rejectedByReach + rejectedByVisibility + rejectedByIk + rejectedByInterference + rejectedByGrasp + feasible (stages are exclusive; the filter short-circuits in the engine's measured cheapest-first order: reach -> IK -> grasp -> visibility -> interference, which decides which single stage a multiply-infeasible candidate is attributed to). Requests that declare no camera / no gripper always report 0 for the corresponding rejection stage. Presentation (wording, colors, meters, ladder-risk mapping, suggestions) is derived client-side and never carried here.
   */
  diagnostics: {
    candidatesGenerated: number;
    rejectedByReach: number;
    /**
     * Rejected because the declared camera cannot see the grasp point (occluded sightline or outside the field of view). Always 0 when the request declares no camera.
     */
    rejectedByVisibility: number;
    rejectedByIk: number;
    rejectedByInterference: number;
    /**
     * Rejected by the geometric grasp gate of the declared gripper (opening width / finger clearance / contact-pair existence). Always 0 when the request declares no gripper.
     */
    rejectedByGrasp: number;
    /**
     * Candidates that passed all five checks (= scored).
     */
    feasible: number;
    /**
     * Candidates actually included in candidates[] (= min(feasible, topN)).
     */
    returned: number;
    /**
     * Smallest distance by which a reach-rejected candidate missed the reachable shell (same length unit as the request geometry). null when nothing was rejected by reach.
     */
    reachNearestMiss: number | null;
    /**
     * Smallest occlusion depth among visibility-rejected candidates (how deep the most-blocking obstacle cuts the closest-to-visible sightline; same length unit as the request geometry). null when no visibility rejection has a measurable occlusion depth (e.g. only outside-FOV rejections, or none at all).
     */
    occlusionNearestMiss: number | null;
    /**
     * Smallest opening-width shortfall among grasp-rejected candidates (required width minus the gripper's max opening; same length unit as the request geometry). null when no grasp rejection has a measurable width shortfall (e.g. only contact-pair-missing rejections, or none at all).
     */
    openingNearestMiss: number | null;
  };
}
export interface PoseCandidate {
  rank: number;
  pose?: Pose;
  score: ScoreBreakdown;
}
/**
 * End-effector (hand/tool) pose expressed in a base/world frame. Cartesian.
 */
export interface PoseEndEffector {
  kind: "endEffector";
  frame: CartesianFrame;
}
/**
 * A rigid-body pose in a base/world frame.
 */
export interface CartesianFrame {
  /**
   * x, y, z.
   *
   * @minItems 3
   * @maxItems 3
   */
  position: [number, number, number];
  /**
   * Quaternion x, y, z, w.
   *
   * @minItems 4
   * @maxItems 4
   */
  orientation: [number, number, number, number];
}
/**
 * Pose expressed in the joint space of a named kinematic chain.
 */
export interface PoseJointSpace {
  kind: "jointSpace";
  /**
   * Which kinematic chain (robot) the joint values belong to.
   */
  chainRef: string;
  /**
   * Joint values in chain order.
   */
  joints: number[];
}
/**
 * Per-candidate score breakdown explaining why a pose ranked where it did. Contract v4 (ADR-081): the five booleans mirror the domain-staged filter (visible = Vision domain, withinReach/ikSolvable/interferenceFree = Path domain, graspable = Grasp domain). A returned candidate passed every stage, so all five are true; `visible` / `graspable` are vacuously true when the request declared no camera / no gripper (the request itself carries which case applies).
 */
export interface ScoreBreakdown {
  withinReach: boolean;
  visible: boolean;
  ikSolvable: boolean;
  interferenceFree: boolean;
  graspable: boolean;
  /**
   * objective name -> normalized 0-1 value (absolute basis, so scores are comparable across requests).
   */
  objectiveScores?: {
    [k: string]: number;
  };
  /**
   * Weighted sum of the normalized objective scores.
   */
  totalScore: number;
}
