/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * BFF -> grasp-search service input. Wire form uses camelCase.
 */
export interface GraspSearchRequest {
  /**
   * Internal contract version (see contract-version.json). Mismatch is rejected with 400.
   */
  contractVersion?: number;
  /**
   * Layout DSL schema version this declaration targets, e.g. 'layout/1.0'. References the public schema; not redefined here.
   */
  layoutVersion: string;
  graspSearch: GraspSearchDeclaration;
}
/**
 * The graspSearch declaration. Its detailed shape (hardConstraints / objectives) is owned by the Layout DSL schema named by layoutVersion; kept open here on purpose.
 */
export interface GraspSearchDeclaration {
  /**
   * objective name -> weight. Keys correspond to score breakdown keys.
   */
  objectiveWeights?: {
    [k: string]: number;
  };
  /**
   * How many ranked candidates to return (fallback material for the BFF).
   */
  topN?: number;
  [k: string]: unknown;
}
